Question 1

In [4]:
import numpy as np

In [5]:
arr = np.arange(2,50,3) #numpy array from 2 to 50 with step size 
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


------------

Question 2

l1=[]
l2=[]
i=5
j=5
while(i!=0):
    x= int(input())
    l1.append(x)
    i=i-1
while(j!=0):
    x= int(input())
    l2.append(x)
    j=j-1
arr1 = np.asarray(l1)
arr2 = np.asarray(l2)
arr = np.concatenate((arr1, arr2))
print("The concatenated numpy array is:",arr)
print("The sorted numpy array is:",np.sort(arr))

----------

In [15]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print("The dimensions of the ndarray are",arr.shape)
print("The size of the ndarray is",arr.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
The dimensions of the ndarray are (3, 3)
The size of the ndarray is 9


-------

Question 4

In [18]:
a1 = np.array([1, 2, 3, 4])
print(a1)

[1 2 3 4]


In [19]:
a2 = np.reshape(a1, (-1, 2))
print(a2)

[[1 2]
 [3 4]]


----------

Question 5

In [26]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[10,11,12],[13,14,15],[16,17,18]])


In [25]:
np.vstack((arr1,arr2))


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [24]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

-------

Question 6

In [36]:
arr = np.array([5,6,2,5,0,3,3,5])

(unique, counts) = np.unique(arr, return_counts=True)
frequencies = np.asarray((unique, counts)).T
print("The unique numbers and their count is as follows:")
print(frequencies)

The unique numbers and their count is as follows:
[[0 1]
 [2 1]
 [3 2]
 [5 3]
 [6 1]]
